export const siteConfig = {
	name: "Board-Mind",
	url: "https://Board-Mind.colidevs.com",
	ogImage: "https://Board-Mind.colidevs.com/og.jpg",
	description: "Board-Mind generated by create-coliapp",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
